# Generated by Django 3.0.5 on 2020-04-11 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('statename', models.CharField(choices=[('Maharashtra', 'Maharashtra'), ('Tamil Nadu', 'Tamil Nadu'), ('Delhi', 'Delhi'), ('Rajasthan', 'Rajasthan'), ('Telangana', 'Telangana'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Gujarat', 'Gujarat'), ('Kerala', 'Kerala'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Karnataka', 'Karnataka'), ('Haryana', 'Haryana'), ('Punjab', 'Punjab'), ('West Bengal', 'West Bengal'), ('Bihar', 'Bihar'), ('Odisha', 'Odisha'), ('Uttarakhand', 'Uttarakhand'), ('Assam', 'Assam'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Chandigarh', 'Chandigarh'), ('Chhattisgarh', 'Chhattisgarh'), ('Ladakh', 'Ladakh'), ('Jharkhand', 'Jharkhand'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Goa', 'Goa'), ('Puducherry', 'Puducherry'), ('Tripura', 'Tripura'), ('Manipur', 'Manipur'), ('Mizoram', 'Mizoram'), ('Dadra and Nagar Haveli', 'Dadra and Nagar Haveli'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Daman and Diu', 'Daman and Diu'), ('Lakshadweep', 'Lakshadweep'), ('Meghalaya', 'Meghalaya'), ('Nagaland', 'Nagaland'), ('Sikkim', 'Sikkim')], max_length=30)),
                ('cityname', models.CharField(choices=[('Lohit', 'Lohit')], max_length=30)),
            ],
        ),
    ]
